// actionLabels.js
export const FETCH_WAREHOUSE_USER_REQUEST = 'FETCH_WAREHOUSE_USER_REQUEST';
export const FETCH_WAREHOUSE_USER_SUCCESS = 'FETCH_WAREHOUSE_USER_SUCCESS';
export const FETCH_WAREHOUSE_USER_FAILURE = 'FETCH_WAREHOUSE_USER_FAILURE';
