export const FETCH_SESSION_TYPE_REQUEST = 'FETCH_SESSION_TYPE_REQUEST';
export const FETCH_SESSION_TYPE_SUCCESS = 'FETCH_SESSION_TYPE_SUCCESS';
export const FETCH_SESSION_TYPE_FAILURE = 'FETCH_SESSION_TYPE_FAILURE';